name: sentiment-analysis-playstore
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - pip
  - pip:
      - mlflow==2.19.0
      - pandas==2.2.3
      - scikit-learn==1.8.0
      - matplotlib==3.10.0
